/* AUTO-GENERATED by scripts/w2-merge-overrides.mjs — do not edit */
import { PRIMITIVE_OVERRIDES } from "./overrides/primitives";
import { SCREEN_OVERRIDES as ihl_00_onboarding_login_OVERRIDES } from "./overrides/ihl-00-onboarding-login";
import { SCREEN_OVERRIDES as ihl_00_onboarding_signup_OVERRIDES } from "./overrides/ihl-00-onboarding-signup";
import { SCREEN_OVERRIDES as ihl_00_terms_OVERRIDES } from "./overrides/ihl-00-terms";
import { SCREEN_OVERRIDES as ihl_01_nav_home_OVERRIDES } from "./overrides/ihl-01-nav-home";
import { SCREEN_OVERRIDES as ihl_03_lineage_cross_OVERRIDES } from "./overrides/ihl-03-lineage-cross";
import { SCREEN_OVERRIDES as ihl_03_lineage_growth_detail_OVERRIDES } from "./overrides/ihl-03-lineage-growth-detail";
import { SCREEN_OVERRIDES as ihl_03_lineage_metrics_detail_OVERRIDES } from "./overrides/ihl-03-lineage-metrics-detail";
import { SCREEN_OVERRIDES as ihl_03_lineage_mortality_detail_OVERRIDES } from "./overrides/ihl-03-lineage-mortality-detail";
import { SCREEN_OVERRIDES as ihl_05_obs_context_picker_OVERRIDES } from "./overrides/ihl-05-obs-context-picker";
import { SCREEN_OVERRIDES as ihl_05_obs_detail_similar_OVERRIDES } from "./overrides/ihl-05-obs-detail-similar";
import { SCREEN_OVERRIDES as ihl_05_obs_device_link_OVERRIDES } from "./overrides/ihl-05-obs-device-link";
import { SCREEN_OVERRIDES as ihl_05_obs_input_female_OVERRIDES } from "./overrides/ihl-05-obs-input-female";
import { SCREEN_OVERRIDES as ihl_05_obs_input_male_OVERRIDES } from "./overrides/ihl-05-obs-input-male";
import { SCREEN_OVERRIDES as ihl_05_obs_input_row_OVERRIDES } from "./overrides/ihl-05-obs-input-row";
import { SCREEN_OVERRIDES as ihl_05_obs_search_grid_OVERRIDES } from "./overrides/ihl-05-obs-search-grid";
import { SCREEN_OVERRIDES as ihl_05_obs_template_detail_OVERRIDES } from "./overrides/ihl-05-obs-template-detail";
import { SCREEN_OVERRIDES as ihl_05_obs_template_fork_OVERRIDES } from "./overrides/ihl-05-obs-template-fork";
import { SCREEN_OVERRIDES as ihl_05_obs_template_list_OVERRIDES } from "./overrides/ihl-05-obs-template-list";
import { SCREEN_OVERRIDES as ihl_06_market_auction_bid_OVERRIDES } from "./overrides/ihl-06-market-auction-bid";
import { SCREEN_OVERRIDES as ihl_06_market_browse_OVERRIDES } from "./overrides/ihl-06-market-browse";
import { SCREEN_OVERRIDES as ihl_06_market_detail_board_stage2_OVERRIDES } from "./overrides/ihl-06-market-detail-board-stage2";
import { SCREEN_OVERRIDES as ihl_06_market_detail_board_stage3_OVERRIDES } from "./overrides/ihl-06-market-detail-board-stage3";
import { SCREEN_OVERRIDES as ihl_06_market_detail_board_OVERRIDES } from "./overrides/ihl-06-market-detail-board";
import { SCREEN_OVERRIDES as ihl_06_market_listing_create_OVERRIDES } from "./overrides/ihl-06-market-listing-create";
import { SCREEN_OVERRIDES as ihl_06_market_lottery_apply_OVERRIDES } from "./overrides/ihl-06-market-lottery-apply";
import { SCREEN_OVERRIDES as ihl_06_market_lottery_result_lose_OVERRIDES } from "./overrides/ihl-06-market-lottery-result-lose";
import { SCREEN_OVERRIDES as ihl_06_market_lottery_result_OVERRIDES } from "./overrides/ihl-06-market-lottery-result";
import { SCREEN_OVERRIDES as ihl_06_market_lottery_tab_OVERRIDES } from "./overrides/ihl-06-market-lottery-tab";
import { SCREEN_OVERRIDES as ihl_06_market_priority_queue_lose_OVERRIDES } from "./overrides/ihl-06-market-priority-queue-lose";
import { SCREEN_OVERRIDES as ihl_06_market_priority_queue_OVERRIDES } from "./overrides/ihl-06-market-priority-queue";
import { SCREEN_OVERRIDES as ihl_06_market_priority_tab_OVERRIDES } from "./overrides/ihl-06-market-priority-tab";
import { SCREEN_OVERRIDES as ihl_06_market_social_OVERRIDES } from "./overrides/ihl-06-market-social";
import { SCREEN_OVERRIDES as ihl_07_board_hub_OVERRIDES } from "./overrides/ihl-07-board-hub";
import { SCREEN_OVERRIDES as ihl_07_board_post__OVERRIDES } from "./overrides/ihl-07-board-post---";
import { SCREEN_OVERRIDES as ihl_07_board_thread_post_OVERRIDES } from "./overrides/ihl-07-board-thread-post";
import { SCREEN_OVERRIDES as ihl_08_karma_summary_OVERRIDES } from "./overrides/ihl-08-karma-summary";
import { SCREEN_OVERRIDES as ihl_09_paper_in_progress_OVERRIDES } from "./overrides/ihl-09-paper-in-progress";
import { SCREEN_OVERRIDES as ihl_09_paper_template_fill_OVERRIDES } from "./overrides/ihl-09-paper-template-fill";
import { SCREEN_OVERRIDES as ihl_10_preference_pairwise_OVERRIDES } from "./overrides/ihl-10-preference-pairwise";
import { SCREEN_OVERRIDES as ihl_11_dispute_tworoom_OVERRIDES } from "./overrides/ihl-11-dispute-tworoom";
import { SCREEN_OVERRIDES as ihl_12_settings_hub_OVERRIDES } from "./overrides/ihl-12-settings-hub";
import { SCREEN_OVERRIDES as ihl_12_settings_pii_OVERRIDES } from "./overrides/ihl-12-settings-pii";
import { SCREEN_OVERRIDES as ihl_13_device_registry_OVERRIDES } from "./overrides/ihl-13-device-registry";
import { SCREEN_OVERRIDES as ihl_14_contribution_badge_OVERRIDES } from "./overrides/ihl-14-contribution-badge";
import { SCREEN_OVERRIDES as ihl_16_edit_this_screen_entry_OVERRIDES } from "./overrides/ihl-16-edit-this-screen-entry";
import { SCREEN_OVERRIDES as ihl_16_uibuilder_canvas_OVERRIDES } from "./overrides/ihl-16-uibuilder-canvas";
import { SCREEN_OVERRIDES as ihl_17_world_template_picker_OVERRIDES } from "./overrides/ihl-17-world-template-picker";
import { SCREEN_OVERRIDES as ihl_18_photo_analysis_result_OVERRIDES } from "./overrides/ihl-18-photo-analysis-result";
import { SCREEN_OVERRIDES as ihl_19_component_board_OVERRIDES } from "./overrides/ihl-19-component-board";
import { SCREEN_OVERRIDES as ihl_20_vote_general_OVERRIDES } from "./overrides/ihl-20-vote-general";
import { SCREEN_OVERRIDES as ihl_22_pt_shop_OVERRIDES } from "./overrides/ihl-22-pt-shop";
import { SCREEN_OVERRIDES as ihl_23_gmo_transfer_OVERRIDES } from "./overrides/ihl-23-gmo-transfer";
import { SCREEN_OVERRIDES as ihl_profile_three_metrics_OVERRIDES } from "./overrides/ihl-profile-three-metrics";
import type { CatalogComponent } from "./overrides.types";

/** Merged hand overrides — per-screen files + primitives */
export const COMPONENT_OVERRIDES: Record<string, CatalogComponent> = {
  ...PRIMITIVE_OVERRIDES,
  ...ihl_00_onboarding_login_OVERRIDES,
  ...ihl_00_onboarding_signup_OVERRIDES,
  ...ihl_00_terms_OVERRIDES,
  ...ihl_01_nav_home_OVERRIDES,
  ...ihl_03_lineage_cross_OVERRIDES,
  ...ihl_03_lineage_growth_detail_OVERRIDES,
  ...ihl_03_lineage_metrics_detail_OVERRIDES,
  ...ihl_03_lineage_mortality_detail_OVERRIDES,
  ...ihl_05_obs_context_picker_OVERRIDES,
  ...ihl_05_obs_detail_similar_OVERRIDES,
  ...ihl_05_obs_device_link_OVERRIDES,
  ...ihl_05_obs_input_female_OVERRIDES,
  ...ihl_05_obs_input_male_OVERRIDES,
  ...ihl_05_obs_input_row_OVERRIDES,
  ...ihl_05_obs_search_grid_OVERRIDES,
  ...ihl_05_obs_template_detail_OVERRIDES,
  ...ihl_05_obs_template_fork_OVERRIDES,
  ...ihl_05_obs_template_list_OVERRIDES,
  ...ihl_06_market_auction_bid_OVERRIDES,
  ...ihl_06_market_browse_OVERRIDES,
  ...ihl_06_market_detail_board_stage2_OVERRIDES,
  ...ihl_06_market_detail_board_stage3_OVERRIDES,
  ...ihl_06_market_detail_board_OVERRIDES,
  ...ihl_06_market_listing_create_OVERRIDES,
  ...ihl_06_market_lottery_apply_OVERRIDES,
  ...ihl_06_market_lottery_result_lose_OVERRIDES,
  ...ihl_06_market_lottery_result_OVERRIDES,
  ...ihl_06_market_lottery_tab_OVERRIDES,
  ...ihl_06_market_priority_queue_lose_OVERRIDES,
  ...ihl_06_market_priority_queue_OVERRIDES,
  ...ihl_06_market_priority_tab_OVERRIDES,
  ...ihl_06_market_social_OVERRIDES,
  ...ihl_07_board_hub_OVERRIDES,
  ...ihl_07_board_post__OVERRIDES,
  ...ihl_07_board_thread_post_OVERRIDES,
  ...ihl_08_karma_summary_OVERRIDES,
  ...ihl_09_paper_in_progress_OVERRIDES,
  ...ihl_09_paper_template_fill_OVERRIDES,
  ...ihl_10_preference_pairwise_OVERRIDES,
  ...ihl_11_dispute_tworoom_OVERRIDES,
  ...ihl_12_settings_hub_OVERRIDES,
  ...ihl_12_settings_pii_OVERRIDES,
  ...ihl_13_device_registry_OVERRIDES,
  ...ihl_14_contribution_badge_OVERRIDES,
  ...ihl_16_edit_this_screen_entry_OVERRIDES,
  ...ihl_16_uibuilder_canvas_OVERRIDES,
  ...ihl_17_world_template_picker_OVERRIDES,
  ...ihl_18_photo_analysis_result_OVERRIDES,
  ...ihl_19_component_board_OVERRIDES,
  ...ihl_20_vote_general_OVERRIDES,
  ...ihl_22_pt_shop_OVERRIDES,
  ...ihl_23_gmo_transfer_OVERRIDES,
  ...ihl_profile_three_metrics_OVERRIDES,
};
